language: java

sudo: required

before_install:
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install virtualbox -qq --fix-missing
  - sudo apt-get install linux-headers-generic -q

before_script:
  - which vboxmanage
  - vboxmanage --help
  - vagrant

script:
  - mvn verify
