language: java

sudo: required

before_install:
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install virtualbox -qq --fix-missing

before_script:
  - vboxmanage --help

script:
  - mvn verify

after_script:
  - zip buildlogs.zip /home/travis/build/barclay-reg/vagrant-maven-plugin/target/it/projects/*/build.log
  - echo "Die Logfiles" | mutt -a buildlogs.zip -s "Last LogFiles " VAR_EMAIL
