language: java

sudo: required

before_install:
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install virtualbox -qq --fix-missing
  - sudo apt-get install mutt -qq
  - sudo apt-get install sharutils -qq
  - sudo apt-get install mailx -qq

before_script:
  - vboxmanage --help

script:
  - mvn verify

after_script:
  - zip buildlogs.zip /home/travis/build/barclay-reg/vagrant-maven-plugin/target/it/projects/*/build.log
  - uuencode buildlogs.zip | mailx -s "Die Logfiles" $VAR_EMAIL
